import React, { useMemo, useState } from 'react';
import { Copy, Download, Heart, Search } from 'lucide-react';
import { ToolDefinition } from '../../../types';
import { apiClient } from '../../../services/apiClient';
import { toast } from '../../common/ToastContainer';

const EMOJIS=[['😀','feliz sonrisa','Caras'],['😂','risa lágrimas','Caras'],['😍','amor corazón','Caras'],['🤔','pensando duda','Caras'],['❤️','corazón amor','Símbolos'],['✅','check correcto','Símbolos'],['⚠️','alerta advertencia','Símbolos'],['⭐','estrella favorito','Símbolos'],['👍','pulgar bien','Gestos'],['👏','aplausos','Gestos'],['🙏','gracias manos','Gestos'],['💪','fuerza brazo','Gestos'],['🚀','cohete lanzamiento','Objetos'],['💡','idea bombilla','Objetos'],['📱','teléfono móvil','Objetos'],['💻','computadora','Objetos'],['🔥','fuego tendencia','Naturaleza'],['✨','brillos magia','Naturaleza'],['🌈','arcoíris','Naturaleza'],['🌍','mundo planeta','Naturaleza']] as const;
const PRESETS={Instagram:[1080,1080],Story:[1080,1920],X:[1200,675],LinkedIn:[1200,627]} as const;
const LIMITS:Record<string,number>={Instagram:2200,Story:2200,X:280,LinkedIn:3000};
const xml=(v:string)=>v.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));
const save=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),0)};
async function png(svg:string,w:number,h:number,name:string){const u=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const i=new Image();await new Promise<void>((ok,no)=>{i.onload=()=>ok();i.onerror=()=>no(new Error('No se pudo renderizar'));i.src=u});const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');if(!x)throw new Error('Canvas no disponible');x.drawImage(i,0,0,w,h);save(await new Promise<Blob>((ok,no)=>c.toBlob(b=>b?ok(b):no(new Error('No se pudo exportar')),'image/png')),name)}finally{URL.revokeObjectURL(u)}}

export function CreativeTools({tool}:{tool:ToolDefinition}){
 const [text,setText]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[expires,setExpires]=useState(30);
 const [icon,setIcon]=useState('V'),[iconBg,setIconBg]=useState('#4f46e5'),[iconColor,setIconColor]=useState('#ffffff'),[shape,setShape]=useState('square');
 const [platform,setPlatform]=useState<keyof typeof PRESETS>('Instagram'),[font,setFont]=useState('Arial'),[size,setSize]=useState(72),[weight,setWeight]=useState(700),[align,setAlign]=useState('center'),[fg,setFg]=useState('#ffffff'),[bg,setBg]=useState('#312e81');
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('velyxora:emoji-favorites')||'[]')}catch{return[]}});
 const copy=async(v:string)=>{await navigator.clipboard.writeText(v);toast.success('Copiado al portapapeles')};
 const iconSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" rx="${shape==='circle'?256:96}" fill="${iconBg}"/><text x="256" y="285" text-anchor="middle" font-family="Arial,sans-serif" font-size="230" font-weight="700" fill="${iconColor}">${xml(icon)}</text></svg>`;
 const [w,h]=PRESETS[platform],anchor=align==='left'?'start':align==='right'?'end':'middle',px=align==='left'?w*.08:align==='right'?w*.92:w/2,lines=text.split('\n').slice(0,8);
 const socialSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><rect width="100%" height="100%" fill="${bg}"/><text x="${px}" y="${h/2-(lines.length-1)*size*.6}" text-anchor="${anchor}" font-family="${xml(font)},sans-serif" font-size="${size}" font-weight="${weight}" fill="${fg}">${lines.map((l,n)=>`<tspan x="${px}" dy="${n?size*1.2:0}">${xml(l)}</tspan>`).join('')}</text></svg>`;
 const shown=useMemo(()=>EMOJIS.filter(e=>(category==='Todos'||e[2]===category)&&(!query||`${e[0]} ${e[1]}`.toLowerCase().includes(query.toLowerCase()))),[query,category]);

 if(tool.id==='url-shortener')return <Box><label className="text-xs">URL larga<input value={text} onChange={e=>setText(e.target.value)} placeholder="https://ejemplo.com" className="mt-1 w-full rounded-xl bg-[#08090D] p-3"/></label><select value={expires} onChange={e=>setExpires(+e.target.value)} className="rounded-lg bg-[#08090D] p-2"><option value={7}>7 días</option><option value={30}>30 días</option><option value={90}>90 días</option><option value={365}>1 año</option></select><button disabled={busy||!text.trim()} onClick={async()=>{try{setBusy(true);const d=await apiClient.links.create(text,expires);setResult(location.origin+d.shortPath)}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}} className="min-h-11 rounded-xl bg-indigo-600 px-5 disabled:opacity-50">{busy?'Creando…':'Acortar URL'}</button>{result&&<div className="flex gap-2"><input readOnly value={result} className="min-w-0 flex-1 rounded-xl bg-black/30 p-3"/><button onClick={()=>copy(result)} className="px-4"><Copy/></button></div>}</Box>;
 if(tool.id==='icon-maker')return <section className="grid gap-5 md:grid-cols-2"><Box><input maxLength={2} value={icon} onChange={e=>setIcon(e.target.value)} className="rounded-xl bg-[#08090D] p-3 text-2xl"/><div className="flex gap-4"><input aria-label="Fondo" type="color" value={iconBg} onChange={e=>setIconBg(e.target.value)}/><input aria-label="Color" type="color" value={iconColor} onChange={e=>setIconColor(e.target.value)}/><select value={shape} onChange={e=>setShape(e.target.value)} className="bg-[#08090D] p-2"><option value="square">Cuadrado</option><option value="circle">Círculo</option></select></div><div className="flex gap-2"><button onClick={()=>save(new Blob([iconSvg],{type:'image/svg+xml'}),'velyxora-icon.svg')} className="rounded-xl bg-indigo-600 px-4 py-3"><Download className="mr-2 inline h-4"/>SVG</button><button onClick={()=>void png(iconSvg,512,512,'velyxora-icon.png')} className="rounded-xl border px-4 py-3"><Download className="mr-2 inline h-4"/>PNG</button></div><p className="text-xs text-slate-500">Paquete favicon: POST_BETA.</p></Box><Preview svg={iconSvg}/></section>;
 if(tool.id==='social-text-studio')return <section className="grid gap-5 lg:grid-cols-2"><Box><div className="flex flex-wrap gap-2">{Object.keys(PRESETS).map(p=><button key={p} onClick={()=>setPlatform(p as keyof typeof PRESETS)} className={`rounded-lg px-3 py-2 text-xs ${platform===p?'bg-indigo-600':'bg-white/5'}`}>{p}</button>)}</div><textarea rows={6} value={text} onChange={e=>setText(e.target.value)} placeholder="Texto y emojis ✨" className="rounded-xl bg-[#08090D] p-3"/><div className="grid grid-cols-2 gap-3"><select value={font} onChange={e=>setFont(e.target.value)} className="bg-[#08090D] p-2">{['Arial','Georgia','Verdana','Trebuchet MS','Courier New'].map(f=><option key={f}>{f}</option>)}</select><select value={weight} onChange={e=>setWeight(+e.target.value)} className="bg-[#08090D] p-2"><option value={400}>Normal</option><option value={600}>Semibold</option><option value={700}>Bold</option></select><label className="text-xs">Tamaño {size}px<input type="range" min={24} max={160} value={size} onChange={e=>setSize(+e.target.value)} className="w-full"/></label><select value={align} onChange={e=>setAlign(e.target.value)} className="bg-[#08090D] p-2"><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select><label>Texto <input type="color" value={fg} onChange={e=>setFg(e.target.value)}/></label><label>Fondo <input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></div><p className={text.length>LIMITS[platform]?'text-rose-300':'text-slate-400'}>{text.length}/{LIMITS[platform]} · {w}×{h}</p><button onClick={()=>void png(socialSvg,w,h,`${platform.toLowerCase()}-post.png`)} className="rounded-xl bg-indigo-600 px-4 py-3"><Download className="mr-2 inline h-4"/>Exportar PNG</button></Box><Preview svg={socialSvg}/></section>;
 return <Box><label className="relative"><Search className="absolute left-3 top-3 h-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar: corazón, alerta, idea…" className="w-full rounded-xl bg-[#08090D] py-3 pl-10"/></label><div className="flex flex-wrap gap-2">{['Todos',...new Set(EMOJIS.map(e=>e[2]))].map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-lg px-3 py-2 text-xs ${category===c?'bg-indigo-600':'bg-white/5'}`}>{c}</button>)}</div><div className="grid grid-cols-5 gap-2 sm:grid-cols-10">{shown.map(e=><div key={e[0]} className="relative"><button title={e[1]} onClick={()=>copy(e[0])} className="min-h-11 w-full rounded-xl bg-white/5 text-2xl">{e[0]}</button><button aria-label="Favorito" onClick={()=>{const n=favorites.includes(e[0])?favorites.filter(x=>x!==e[0]):[...favorites,e[0]];setFavorites(n);localStorage.setItem('velyxora:emoji-favorites',JSON.stringify(n))}} className="absolute -right-1 -top-1"><Heart className={`h-3 ${favorites.includes(e[0])?'fill-rose-400 text-rose-400':'text-slate-500'}`}/></button></div>)}</div></Box>;
}
function Box({children}:{children:React.ReactNode}){return <section className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-[#101218] p-6">{children}</section>}
function Preview({svg}:{svg:string}){return <div className="grid place-items-center rounded-2xl border border-white/10 bg-[#101218] p-4"><img src={`data:image/svg+xml,${encodeURIComponent(svg)}`} alt="Vista previa visual" className="max-h-[560px] max-w-full"/></div>}
