import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import { BaseConversionEngine } from "./ConversionEngine";
import { ConversionOptions, ConversionResult } from "../types/conversions";
import { ENV } from "../config/env";
import { logger } from "../utils/logger";

export class LibreOfficeEngine extends BaseConversionEngine {
  readonly name = "LibreOfficeEngine";

  readonly supportedInputFormats = [
    "docx",
    "doc",
    "pptx",
    "ppt",
    "xlsx",
    "xls",
    "odt",
    "ods",
    "odp",
    "rtf",
    "txt",
  ];

  readonly supportedOutputFormats = ["pdf", "html", "txt", "csv"];

  private availableCache: boolean | null = null;

  async isAvailable(): Promise<boolean> {
    if (this.availableCache !== null) return this.availableCache;

    return new Promise<boolean>((resolve) => {
      const proc = spawn(ENV.LIBREOFFICE_PATH, ["--version"]);
      proc.on("error", () => {
        this.availableCache = false;
        resolve(false);
      });
      proc.on("close", (code) => {
        this.availableCache = code === 0;
        resolve(this.availableCache);
      });
    });
  }

  async convert(
    inputPath: string,
    outputPath: string,
    options: ConversionOptions,
    onProgress?: (progress: number, message?: string) => void,
  ): Promise<ConversionResult> {
    const isReady = await this.isAvailable();
    if (!isReady) {
      throw new Error(
        `LibreOffice binary is not installed or available on this host (executable: '${ENV.LIBREOFFICE_PATH}'). ` +
          `To enable Office document conversions, install LibreOffice headless on the host system: ` +
          `'sudo apt-get install -y libreoffice-writer libreoffice-calc libreoffice-impress'.`,
      );
    }

    if (!fs.existsSync(inputPath)) {
      throw new Error(`Source document does not exist: ${inputPath}`);
    }

    const outDir = path.dirname(outputPath);
    const targetFormat = path
      .extname(outputPath)
      .replace(/^\./, "")
      .toLowerCase();

    const args = [
      "--headless",
      "--convert-to",
      targetFormat,
      "--outdir",
      outDir,
      inputPath,
    ];

    logger.info(
      `Spawning LibreOffice: ${ENV.LIBREOFFICE_PATH} ${args.join(" ")}`,
    );
    if (onProgress)
      onProgress(-1, "Converting document via LibreOffice headless...");

    return new Promise<ConversionResult>((resolve, reject) => {
      const proc = spawn(ENV.LIBREOFFICE_PATH, args);

      let stderrLog = "";
      proc.stderr.on("data", (d) => {
        stderrLog += d.toString();
      });

      proc.on("error", (err) => {
        logger.error(`LibreOffice error: ${err.message}`);
        reject(err);
      });

      proc.on("close", (code) => {
        if (code !== 0) {
          return reject(
            new Error(
              `LibreOffice conversion failed with exit code ${code}: ${stderrLog}`,
            ),
          );
        }

        // Output filename generated by LibreOffice defaults to input basename + target extension
        const inputBasename = path.parse(inputPath).name;
        const generatedFile = path.join(
          outDir,
          `${inputBasename}.${targetFormat}`,
        );

        if (!fs.existsSync(generatedFile)) {
          return reject(
            new Error(
              `Conversion finished but output document was not found at ${generatedFile}`,
            ),
          );
        }

        // Rename to requested outputPath if different
        if (generatedFile !== outputPath) {
          fs.renameSync(generatedFile, outputPath);
        }

        const stat = fs.statSync(outputPath);
        resolve({
          outputPath,
          outputFilename: path.basename(outputPath),
          mimeType:
            targetFormat === "pdf"
              ? "application/pdf"
              : "application/octet-stream",
          size: stat.size,
        });
      });
    });
  }
}

export const libreOfficeEngine = new LibreOfficeEngine();
