import { ToolDefinition } from '../types';

export const TOOL_REGISTRY: ToolDefinition[] = [
  // ==================== IMAGE TOOLS ====================
  {
    id: 'png-to-jpg',
    slug: 'png-to-jpg',
    name: 'PNG a JPG',
    description: 'Convierte imágenes PNG a formato JPEG con fondo opaco y ajuste de compresión.',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'FileImage',
    inputTypes: ['image/png'],
    outputTypes: ['image/jpeg'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['png', 'jpg', 'jpeg', 'convertir', 'imagen', 'transparencia'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'jpg-to-png',
    slug: 'jpg-to-png',
    name: 'JPG a PNG',
    description: 'Convierte fotografías JPG a formato PNG sin compresión con pérdida.',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'FileImage',
    inputTypes: ['image/jpeg', 'image/jpg'],
    outputTypes: ['image/png'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['jpg', 'png', 'convertir', 'imagen'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'png-to-webp',
    slug: 'png-to-webp',
    name: 'PNG a WebP',
    description: 'Reduce el peso de imágenes PNG hasta un 80% preservando transparencia en WebP moderno.',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'Sparkles',
    inputTypes: ['image/png'],
    outputTypes: ['image/webp'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['webp', 'png', 'optimizar', 'web', 'comprimir'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'jpg-to-webp',
    slug: 'jpg-to-webp',
    name: 'JPG a WebP',
    description: 'Transforma imágenes JPEG al formato WebP de última generación para carga web ultra rápida.',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'Zap',
    inputTypes: ['image/jpeg', 'image/jpg'],
    outputTypes: ['image/webp'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['jpg', 'webp', 'compresion', 'rendimiento', 'google'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Compresor de Imágenes',
    description: 'Reduce el tamaño de archivo en KB/MB ajustando calidad visual, dimensiones y formato.',
    category: 'image',
    subcategory: 'Optimización',
    icon: 'Minimize2',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/jpeg', 'image/webp'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['comprimir', 'reducir', 'peso', 'kb', 'mb', 'optimizar'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Redimensionar Imagen',
    description: 'Escala dimensiones por píxeles exactos, porcentaje o presets de redes sociales.',
    category: 'image',
    subcategory: 'Edición',
    icon: 'Maximize2',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['redimensionar', 'escalar', 'resize', 'instagram', 'youtube', 'dimensiones'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'image-cropper',
    public: false,
    slug: 'image-cropper',
    name: 'Recortador de Imágenes',
    description: 'Recorta áreas específicas con proporciones libres, cuadradas (1:1) o 16:9 con preview en vivo.',
    category: 'image',
    subcategory: 'Edición',
    icon: 'Crop',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['recortar', 'crop', 'cuadrado', 'foto de perfil', 'avatar'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'sticker-maker',
    slug: 'sticker-maker',
    name: 'Crear Sticker',
    description: 'Encuadra una imagen y genera un sticker WebP estático de 512 × 512, localmente en tu navegador.',
    category: 'image',
    subcategory: 'Edición',
    icon: 'Sticker',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/webp'],
    acceptedExtensions: ['png', 'jpg', 'jpeg', 'webp'],
    acceptedMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['sticker', 'pegatina', 'webp', '512', 'cuadrado', 'whatsapp', 'imagen'],
    popular: true,
    isClientReady: true,
    creditsCost: 0,
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    name: 'Imagen a Base64',
    description: 'Convierte cualquier imagen a Data URL Base64 para incrustar directamente en HTML/CSS.',
    category: 'image',
    subcategory: 'Developer',
    icon: 'Binary',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml', 'image/gif'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['base64', 'dataurl', 'html', 'css', 'embed'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Generador de Favicon',
    description: 'Crea paquetes de favicon de 16x16, 32x32, 48x48 y 180x180 px listos para tu sitio web.',
    category: 'image',
    subcategory: 'Web',
    icon: 'Globe',
    inputTypes: ['image/png', 'image/jpeg', 'image/svg+xml'],
    outputTypes: ['application/zip'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['favicon', 'ico', 'apple-touch-icon', 'web', 'icono'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'color-picker-image',
    slug: 'color-picker-image',
    name: 'Extractor de Colores',
    description: 'Extrae la paleta cromática dominante y códigos HEX/RGB haciendo clic en cualquier foto.',
    category: 'image',
    subcategory: 'Utilidades',
    icon: 'Pipette',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['color', 'pipette', 'paleta', 'hex', 'rgb', 'diseño'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'svg-to-png',
    slug: 'svg-to-png',
    name: 'SVG a PNG',
    description: 'Renderiza gráficos vectoriales SVG a mapas de bits PNG en alta definición (1x, 2x, 4x).',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'FileImage',
    inputTypes: ['image/svg+xml', 'text/plain'],
    outputTypes: ['image/png'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['svg', 'png', 'vector', 'escalar', 'transparencia'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'svg-to-jpg',
    slug: 'svg-to-jpg',
    name: 'SVG a JPG',
    description: 'Convierte vectores SVG a fotografías JPG con fondo blanco opaco y calidad configurable.',
    category: 'image',
    subcategory: 'Conversión',
    icon: 'FileImage',
    inputTypes: ['image/svg+xml', 'text/plain'],
    outputTypes: ['image/jpeg'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['svg', 'jpg', 'jpeg', 'vector', 'exportar'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'image-filters',
    slug: 'image-filters',
    name: 'Filtros y Ajustes de Imagen',
    description: 'Modifica brillo, contraste, saturación, escala de grises, sepia, invertido y desenfoque.',
    category: 'image',
    subcategory: 'Edición',
    icon: 'Sliders',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/jpeg', 'image/png'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['filtros', 'brillo', 'contraste', 'grises', 'sepia', 'edicion'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'image-watermark',
    slug: 'image-watermark',
    name: 'Marca de Agua en Imágenes',
    description: 'Añade textos de copyright o marcas de agua con control de opacidad, tamaño y posición.',
    category: 'image',
    subcategory: 'Edición',
    icon: 'Stamp',
    inputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/jpeg'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['watermark', 'marca de agua', 'copyright', 'firma', 'proteger'],
    popular: false,
    isClientReady: true
  },

  // ==================== VIDEO TOOLS ====================
  {
    id: 'video-frame-extractor',
    slug: 'video-frame-extractor',
    name: 'Extractor de Fotogramas',
    description: 'Captura imágenes fijas en resolución nativa de cualquier fotograma exacto del video.',
    category: 'video',
    subcategory: 'Extracción',
    icon: 'Film',
    inputTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    outputTypes: ['image/png', 'image/jpeg'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['fotograma', 'frame', 'captura', 'thumbnail', 'foto de video'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'video-metadata-inspector',
    slug: 'video-metadata-inspector',
    name: 'Inspector Técnico de Video',
    description: 'Muestra metadata local y usa FFprobe temporalmente para códecs y parámetros técnicos fiables.',
    category: 'video',
    subcategory: 'Análisis',
    icon: 'Info',
    inputTypes: ['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime'],
    outputTypes: ['text/json'],
    processingMode: 'HYBRID',
    engine: 'browser-metadata+server-ffprobe',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['metadata', 'inspector', 'resolucion', 'fps', 'codec', 'duracion'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'video-to-mp3',
    slug: 'video-to-mp3',
    name: 'Video a Audio (WAV / MP3)',
    description: 'Extrae la pista de audio de videos MP4 o WebM a formato de audio estándar.',
    category: 'video',
    subcategory: 'Conversión',
    icon: 'Music',
    inputTypes: ['video/mp4', 'video/webm'],
    outputTypes: ['audio/wav', 'audio/mpeg'],
    processingMode: 'SERVER_SIDE',
    engine: 'server-ffmpeg',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['mp4', 'mp3', 'wav', 'extraer audio', 'musica', 'sonido'],
    popular: true,
    requiresServer: true,
    serverEngineNotice: 'Requiere FFmpeg para codificar bytes MP3 reales.',
    isClientReady: false
  },
  {
    id: 'video-compressor',
    slug: 'video-compressor',
    name: 'Compresor de Video (FFmpeg)',
    description: 'Comprime videos mediante CRF y codificación H.264/HEVC para Discord, WhatsApp y correo.',
    category: 'video',
    subcategory: 'Optimización',
    icon: 'Video',
    inputTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    outputTypes: ['video/mp4'],
    processingMode: 'SERVER_SIDE',
    engine: 'server-ffmpeg',
    requiresServer: true,
    keywords: ['comprimir video', 'h264', 'crf', 'discord', 'reducir mp4'],
    popular: true,
    isClientReady: false
  },
  { id: 'video-to-wav', slug: 'video-to-wav', name: 'Video a WAV', description: 'Extrae el audio del video como WAV sin compresión.', category: 'video', subcategory: 'Conversión', icon: 'Music', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['audio/wav'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['video','wav','extraer audio'], isClientReady: false },
  { id: 'video-to-gif', slug: 'video-to-gif', name: 'Video a GIF', description: 'Convierte un fragmento de video en una animación GIF.', category: 'video', subcategory: 'Conversión', icon: 'Film', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['image/gif'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['video','gif','animación'], isClientReady: false },
  { id: 'video-trimmer', slug: 'video-trimmer', name: 'Recortar video', description: 'Selecciona el inicio y final del fragmento que quieres conservar.', category: 'video', subcategory: 'Edición', icon: 'Scissors', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['video/mp4'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['recortar','trim','cortar video'], isClientReady: false },
  { id: 'video-mute', slug: 'video-mute', name: 'Silenciar video', description: 'Elimina completamente la pista de audio y conserva la imagen.', category: 'video', subcategory: 'Edición', icon: 'VolumeX', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['video/mp4'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['silenciar','quitar audio','mute'], isClientReady: false },
  { id: 'video-speed', slug: 'video-speed', name: 'Cambiar velocidad de video', description: 'Acelera o ralentiza el video manteniendo audio e imagen sincronizados.', category: 'video', subcategory: 'Edición', icon: 'Gauge', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['video/mp4'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['velocidad','acelerar','ralentizar'], isClientReady: false },
  { id: 'video-resize', slug: 'video-resize', name: 'Cambiar resolución de video', description: 'Redimensiona el video a una resolución estándar.', category: 'video', subcategory: 'Edición', icon: 'Maximize2', inputTypes: ['video/mp4','video/webm','video/quicktime'], outputTypes: ['video/mp4'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['resolución','720p','1080p','redimensionar'], isClientReady: false },
  { id: 'mp4-to-webm', slug: 'mp4-to-webm', name: 'MP4 a WebM', description: 'Convierte video MP4 al formato WebM.', category: 'video', subcategory: 'Conversión', icon: 'Video', inputTypes: ['video/mp4'], outputTypes: ['video/webm'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['mp4','webm','convertir'], isClientReady: false },
  { id: 'webm-to-mp4', slug: 'webm-to-mp4', name: 'WebM a MP4', description: 'Convierte video WebM al formato MP4 compatible.', category: 'video', subcategory: 'Conversión', icon: 'Video', inputTypes: ['video/webm'], outputTypes: ['video/mp4'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, supportsPreview: true, keywords: ['webm','mp4','convertir'], isClientReady: false },

  // ==================== AUDIO TOOLS ====================
  {
    id: 'audio-trimmer',
    slug: 'audio-trimmer',
    name: 'Recortador de Audio',
    description: 'Recorta pistas de audio con precisión de milisegundos y exporta en WAV de alta fidelidad.',
    category: 'audio',
    subcategory: 'Edición',
    icon: 'Scissors',
    inputTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/mp4'],
    outputTypes: ['audio/wav'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-webaudio',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['recortar audio', 'cortar', 'trim', 'tono de llamada', 'wav'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'audio-channel-converter',
    public: false,
    slug: 'audio-channel-converter',
    name: 'Convertidor Estéreo / Mono',
    description: 'Convierte audio estéreo a pista monofónica balanceada o duplica canales.',
    category: 'audio',
    subcategory: 'Procesamiento',
    icon: 'Radio',
    inputTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg'],
    outputTypes: ['audio/wav'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-webaudio',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['mono', 'estereo', 'canales', 'audio', 'audio context'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'audio-format-converter',
    public: false,
    slug: 'audio-format-converter',
    name: 'Conversor de Audio (WAV / FLAC / MP3)',
    description: 'Transcodificación de alta fidelidad entre contenedores de audio digital.',
    category: 'audio',
    subcategory: 'Conversión',
    icon: 'Volume2',
    inputTypes: ['audio/wav', 'audio/mpeg', 'audio/flac', 'audio/ogg'],
    outputTypes: ['audio/mp3', 'audio/wav'],
    processingMode: 'HYBRID',
    engine: 'server-ffmpeg',
    requiresServer: true,
    serverEngineNotice: 'Transcodificación avanzada multiformato provista por servicio FFmpeg backend.',
    keywords: ['mp3', 'flac', 'wav', 'audio converter', 'bitrate'],
    popular: true,
    isClientReady: false
  },
  { id: 'wav-to-mp3', slug: 'wav-to-mp3', name: 'WAV a MP3', description: 'Convierte audio WAV a MP3 real con bitrate configurable.', category: 'audio', subcategory: 'Conversión', icon: 'Music', inputTypes: ['audio/wav'], outputTypes: ['audio/mpeg'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, keywords: ['wav','mp3'], isClientReady: false },
  { id: 'mp3-to-wav', slug: 'mp3-to-wav', name: 'MP3 a WAV', description: 'Convierte audio MP3 a WAV PCM sin compresión.', category: 'audio', subcategory: 'Conversión', icon: 'Music', inputTypes: ['audio/mpeg'], outputTypes: ['audio/wav'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, keywords: ['mp3','wav'], isClientReady: false },
  { id: 'audio-bitrate', slug: 'audio-bitrate', name: 'Cambiar bitrate de audio', description: 'Equilibra calidad y tamaño. Subir el bitrate no recupera calidad perdida.', category: 'audio', subcategory: 'Optimización', icon: 'SlidersHorizontal', inputTypes: ['audio/mpeg','audio/wav','audio/flac','audio/ogg'], outputTypes: ['audio/mpeg'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, keywords: ['bitrate','audio','calidad'], isClientReady: false },
  { id: 'audio-normalize', slug: 'audio-normalize', name: 'Normalizar volumen', description: 'Ajusta automáticamente el audio para obtener un nivel más uniforme.', category: 'audio', subcategory: 'Procesamiento', icon: 'AudioLines', inputTypes: ['audio/mpeg','audio/wav','audio/flac','audio/ogg'], outputTypes: ['audio/mpeg'], processingMode: 'SERVER_SIDE', engine: 'server-ffmpeg', requiresServer: true, keywords: ['normalizar','volumen','loudness'], isClientReady: false },
  {
    id: 'text-to-speech',
    slug: 'text-to-speech',
    name: 'Texto a Voz (leer en voz alta)',
    description: 'Lee un texto en voz alta con tu navegador: elige voz, velocidad y tono. No genera archivo descargable.',
    category: 'audio',
    subcategory: 'Voz',
    icon: 'Volume2',
    inputTypes: ['text/plain'],
    outputTypes: ['audio/speech'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-speech',
    supportsBatch: false,
    supportsPreview: false,
    keywords: ['texto a voz', 'tts', 'leer', 'voz', 'speech', 'audio'],
    popular: false,
    isClientReady: true,
  },

  // ==================== DEVELOPER TOOLS ====================
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'Formateador & Validador JSON',
    description: 'Indenta, valida sintaxis, minifica y resalta errores de estructuras JSON complejas.',
    category: 'developer',
    subcategory: 'Formatos',
    icon: 'Code2',
    inputTypes: ['application/json', 'text/plain'],
    outputTypes: ['application/json'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['json', 'formatear', 'pretty print', 'validar', 'minificar'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    name: 'Decodificador JWT',
    description: 'Decodifica e inspecciona cabeceras, payload y expiración de un JWT de forma local. No verifica la firma ni la validez criptográfica.',
    category: 'developer',
    subcategory: 'Seguridad',
    icon: 'KeyRound',
    inputTypes: ['text/plain'],
    outputTypes: ['application/json'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['jwt', 'token', 'auth', 'bearer', 'decode', 'claims'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    name: 'Generador Criptográfico de Hash',
    description: 'Calcula huellas unidireccionales SHA-256, SHA-384 y SHA-512 utilizando Web Crypto en el navegador.',
    category: 'developer',
    subcategory: 'Criptografía',
    icon: 'ShieldCheck',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-crypto',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['hash', 'sha256', 'sha384', 'sha512', 'checksum', 'crypto'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'Generador de UUID / GUID',
    description: 'Genera identificadores universales únicos RFC 4122 v4 en lotes personalizados.',
    category: 'developer',
    subcategory: 'Identificadores',
    icon: 'Fingerprint',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-crypto',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['uuid', 'guid', 'v4', 'random', 'identificador'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'base64-text-converter',
    public: false,
    slug: 'base64-text-converter',
    name: 'Codificador / Decodificador Base64',
    description: 'Convierte cadenas de texto UTF-8 a Base64 estándar o URL-Safe con verificación de errores.',
    category: 'developer',
    subcategory: 'Codificación',
    icon: 'Binary',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['base64', 'encode', 'decode', 'btoa', 'atob'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'url-encoder-decoder',
    public: false,
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    description: 'Codifica y decodifica parámetros de consulta y URLs completas según RFC 3986.',
    category: 'developer',
    subcategory: 'Web',
    icon: 'Link',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['url', 'uri', 'encode', 'decode', 'query param', 'percent encoding'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'regex-tester',
    public: false,
    slug: 'regex-tester',
    name: 'Probador de Expresiones Regulares',
    description: 'Prueba patrones RegExp en tiempo real con resaltado de coincidencias y grupos de captura.',
    category: 'developer',
    subcategory: 'Texto',
    icon: 'SearchCode',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['regex', 'regexp', 'expresiones regulares', 'match', 'test'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'csv-to-json',
    slug: 'csv-to-json',
    name: 'Conversor CSV a JSON',
    description: 'Transforma hojas de cálculo y datos CSV a JSON estructurado con autodetección de delimitador.',
    category: 'developer',
    subcategory: 'Datos',
    icon: 'FileSpreadsheet',
    inputTypes: ['text/csv', 'text/plain'],
    outputTypes: ['application/json'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['csv', 'json', 'convertir', 'tabla', 'datos', 'excel'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'json-to-csv',
    slug: 'json-to-csv',
    name: 'Conversor JSON a CSV',
    description: 'Convierte listas y arrays de objetos JSON en hojas de cálculo CSV compatibles con Excel.',
    category: 'developer',
    subcategory: 'Datos',
    icon: 'Table',
    inputTypes: ['application/json', 'text/plain'],
    outputTypes: ['text/csv'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['json', 'csv', 'excel', 'exportar', 'tabla'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'markdown-to-html',
    slug: 'markdown-to-html',
    name: 'Markdown a HTML',
    description: 'Convierte sintaxis Markdown (.md) a código HTML limpio con previsualización en vivo.',
    category: 'developer',
    subcategory: 'Formatos',
    icon: 'FileCode',
    inputTypes: ['text/markdown', 'text/plain'],
    outputTypes: ['text/html'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['markdown', 'html', 'md', 'readme', 'convertir'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    name: 'Conversor de Colores (HEX / RGB / HSL / CMYK)',
    description: 'Calcula al instante las equivalencias entre modelos de color digitales y de imprenta.',
    category: 'developer',
    subcategory: 'Diseño',
    icon: 'Palette',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['color', 'hex', 'rgb', 'hsl', 'cmyk', 'conversor'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'diff-checker',
    slug: 'diff-checker',
    name: 'Comparador de Texto y Código (Diff)',
    description: 'Compara dos fragmentos de texto o código línea por línea detectando adiciones y eliminaciones.',
    category: 'developer',
    subcategory: 'Utilidades',
    icon: 'GitCompare',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['diff', 'comparar', 'diferencias', 'git', 'codigo'],
    popular: true,
    isClientReady: true
  },

  // ==================== TEXT TOOLS ====================
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Contador de Palabras & Caracteres',
    description: 'Métricas completas de palabras, caracteres, líneas, párrafos y tiempo estimado de lectura.',
    category: 'text',
    subcategory: 'Estadísticas',
    icon: 'FileText',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['contar palabras', 'caracteres', 'lineas', 'estadisticas texto', 'lectura'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Conversor de Mayúsculas y Minúsculas',
    description: 'Transforma texto a UPPERCASE, lowercase, Title Case, camelCase, snake_case o kebab-case.',
    category: 'text',
    subcategory: 'Transformación',
    icon: 'Type',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['mayusculas', 'minusculas', 'camelcase', 'snake_case', 'kebab-case', 'capitalizar'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'line-cleaner-sorter',
    public: false,
    slug: 'line-cleaner-sorter',
    name: 'Limpiador & Ordenador de Líneas',
    description: 'Elimina líneas duplicadas, limpia espacios en blanco y ordena alfabéticamente (A-Z, Z-A).',
    category: 'text',
    subcategory: 'Organización',
    icon: 'ListFilter',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['duplicados', 'ordenar', 'limpiar lineas', 'espacios', 'alfabetico'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'slug-generator',
    public: false,
    slug: 'slug-generator',
    name: 'Generador de Slugs URL',
    description: 'Convierte títulos y frases en slugs limpios compatibles con SEO y URLs amigables.',
    category: 'text',
    subcategory: 'SEO',
    icon: 'Hash',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['slug', 'url', 'seo', 'permalink', 'kebab'],
    popular: false,
    isClientReady: true
  },

  // ==================== QR & BARCODE TOOLS ====================
  {
    id: 'qr-generator',
    slug: 'qr-generator',
    name: 'Generador de Código QR Profesional',
    description: 'Crea códigos QR personalizados para URLs, Texto libre, redes WiFi seguras, Email y vCards.',
    category: 'qr-barcode',
    subcategory: 'Generación',
    icon: 'QrCode',
    inputTypes: ['text/plain'],
    outputTypes: ['image/png', 'image/svg+xml'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-qrcode',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['qr', 'codigo qr', 'wifi', 'vcard', 'url qr', 'vector'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'barcode-generator',
    slug: 'barcode-generator',
    name: 'Generador de Código de Barras (Code 128)',
    description: 'Genera códigos de barras industriales Code 128 nítidos con exportación PNG de alta resolución.',
    category: 'qr-barcode',
    subcategory: 'Generación',
    icon: 'ScanBarcode',
    inputTypes: ['text/plain'],
    outputTypes: ['image/png'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['barcode', 'codigo de barras', 'code128', 'ean', 'inventario'],
    popular: false,
    isClientReady: true
  },

  // ==================== WHATSAPP TOOLS (CLIENT_ONLY) ====================
  {
    id: 'whatsapp-link-generator',
    slug: 'whatsapp-link-generator',
    name: 'Generador de enlace wa.me',
    description: 'Crea un enlace de WhatsApp con número y mensaje opcional, localmente en tu navegador.',
    category: 'whatsapp',
    subcategory: 'Enlaces',
    icon: 'Link',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: false,
    keywords: ['whatsapp', 'wa.me', 'enlace', 'link', 'chat', 'numero'],
    popular: true,
    isClientReady: true,
  },
  {
    id: 'whatsapp-message-builder',
    slug: 'whatsapp-message-builder',
    name: 'Constructor de mensajes de WhatsApp',
    description: 'Redacta un mensaje, revisa su versión codificada y combínalo con un número.',
    category: 'whatsapp',
    subcategory: 'Mensajes',
    icon: 'MessageSquare',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['whatsapp', 'mensaje', 'texto', 'codificado', 'url encode', 'chat'],
    popular: false,
    isClientReady: true,
  },
  {
    id: 'whatsapp-qr-generator',
    slug: 'whatsapp-qr-generator',
    name: 'Código QR de WhatsApp',
    description: 'Genera un código QR descargable para un enlace de WhatsApp, localmente.',
    category: 'whatsapp',
    subcategory: 'QR',
    icon: 'QrCode',
    inputTypes: ['text/plain'],
    outputTypes: ['image/png'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-qrcode',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['whatsapp', 'qr', 'codigo qr', 'escanear', 'enlace'],
    popular: false,
    isClientReady: true,
  },

  // ==================== MEDIA DOWNLOADER ====================
  {
    id: 'media-url-analyzer',
    slug: 'media-url-analyzer',
    name: 'Analizador & Descargador de Medios',
    description: 'Analiza enlaces de YouTube, TikTok, Facebook, Instagram, Twitter, Vimeo y Reddit con previsualización.',
    category: 'media-downloader',
    subcategory: 'Media URL',
    icon: 'DownloadCloud',
    inputTypes: ['text/url'],
    outputTypes: ['video/mp4', 'audio/mpeg'],
    processingMode: 'HYBRID',
    engine: 'server-ytdlp',
    requiresServer: true,
    serverEngineNotice: 'Análisis de metadatos y embeds activo; la descarga de flujos combinados requiere microservicio yt-dlp + ffmpeg.',
    keywords: ['youtube', 'tiktok', 'instagram', 'twitter', 'facebook', 'descargar video', 'vimeo', 'reels'],
    popular: true,
    isClientReady: true,
    public: false
  },

  // ==================== PDF & DOCUMENTS ====================
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    name: 'Imágenes a PDF',
    description: 'Compila múltiples imágenes JPG o PNG en un único documento PDF ordenado y escalado.',
    category: 'pdf',
    subcategory: 'Creación',
    icon: 'FileSpreadsheet',
    inputTypes: ['image/jpeg', 'image/png', 'image/webp'],
    outputTypes: ['application/pdf'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-canvas',
    supportsBatch: true,
    supportsPreview: true,
    keywords: ['pdf', 'fotos a pdf', 'imagenes a pdf', 'escaner', 'documento'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'text-to-pdf',
    slug: 'text-to-pdf',
    name: 'Texto a PDF',
    description: 'Genera documentos PDF multipágina formateados a partir de texto o notas.',
    category: 'pdf',
    subcategory: 'Creación',
    icon: 'FileText',
    inputTypes: ['text/plain'],
    outputTypes: ['application/pdf'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['texto a pdf', 'documento', 'notas a pdf', 'exportar pdf'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Unir PDFs (Merge)',
    description: 'Combina múltiples PDF en un único documento, directamente en tu navegador.',
    category: 'pdf',
    subcategory: 'Manipulación',
    icon: 'Layers',
    inputTypes: ['application/pdf'],
    outputTypes: ['application/pdf'],
    acceptedExtensions: ['pdf'],
    acceptedMimeTypes: ['application/pdf'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-pdf',
    supportsBatch: true,
    supportsPreview: false,
    keywords: ['unir pdf', 'merge', 'combinar pdf'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Dividir PDF (Split)',
    description: 'Extrae un rango de páginas o separa cada página en un PDF, en tu navegador.',
    category: 'pdf',
    subcategory: 'Manipulación',
    icon: 'Scissors',
    inputTypes: ['application/pdf'],
    outputTypes: ['application/pdf', 'application/zip'],
    acceptedExtensions: ['pdf'],
    acceptedMimeTypes: ['application/pdf'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-pdf',
    supportsBatch: false,
    supportsPreview: false,
    keywords: ['dividir pdf', 'split', 'separar paginas', 'extraer paginas'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word (DOCX) a PDF',
    description: 'Conversión fidedigna de documentos Microsoft Word a estándar PDF.',
    category: 'documents',
    subcategory: 'Conversión',
    icon: 'FileText',
    inputTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    acceptedExtensions: ['docx'],
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    outputTypes: ['application/pdf'],
    processingMode: 'SERVER_SIDE',
    engine: 'server-libreoffice',
    requiresServer: true,
    serverEngineNotice: 'Requiere LibreOffice headless en el backend.',
    keywords: ['word', 'docx', 'pdf', 'libreoffice', 'convertir documento'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'xlsx-to-pdf', slug: 'xlsx-to-pdf', name: 'Excel (XLSX) a PDF',
    description: 'Convierte hojas de cálculo XLSX a PDF mediante LibreOffice.', category: 'documents', subcategory: 'Conversión', icon: 'Sheet',
    inputTypes: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], outputTypes: ['application/pdf'],
    acceptedExtensions: ['xlsx'], acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    processingMode: 'SERVER_SIDE', engine: 'server-libreoffice', requiresServer: true,
    serverEngineNotice: 'Requiere LibreOffice headless en el backend.', keywords: ['excel', 'xlsx', 'pdf', 'libreoffice'], popular: true, isClientReady: true
  },
  {
    id: 'pptx-to-pdf', slug: 'pptx-to-pdf', name: 'PowerPoint (PPTX) a PDF',
    description: 'Convierte presentaciones PPTX a PDF mediante LibreOffice.', category: 'documents', subcategory: 'Conversión', icon: 'Presentation',
    inputTypes: ['application/vnd.openxmlformats-officedocument.presentationml.presentation'], outputTypes: ['application/pdf'],
    acceptedExtensions: ['pptx'], acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    processingMode: 'SERVER_SIDE', engine: 'server-libreoffice', requiresServer: true,
    serverEngineNotice: 'Requiere LibreOffice headless en el backend.', keywords: ['powerpoint', 'pptx', 'pdf', 'libreoffice'], popular: true, isClientReady: true
  },
  {
    id: 'odt-to-pdf', slug: 'odt-to-pdf', name: 'OpenDocument (ODT) a PDF', description: 'Convierte documentos ODT a PDF mediante LibreOffice.', category: 'documents', subcategory: 'Conversión', icon: 'FileText', inputTypes: ['application/vnd.oasis.opendocument.text'], outputTypes: ['application/pdf'], acceptedExtensions: ['odt'], acceptedMimeTypes: ['application/vnd.oasis.opendocument.text'], processingMode: 'SERVER_SIDE', engine: 'server-libreoffice', requiresServer: true, keywords: ['odt','opendocument','writer','pdf'], isClientReady: true
  },
  {
    id: 'ods-to-pdf', slug: 'ods-to-pdf', name: 'OpenDocument (ODS) a PDF', description: 'Convierte hojas ODS a PDF mediante LibreOffice.', category: 'documents', subcategory: 'Conversión', icon: 'Sheet', inputTypes: ['application/vnd.oasis.opendocument.spreadsheet'], outputTypes: ['application/pdf'], acceptedExtensions: ['ods'], acceptedMimeTypes: ['application/vnd.oasis.opendocument.spreadsheet'], processingMode: 'SERVER_SIDE', engine: 'server-libreoffice', requiresServer: true, keywords: ['ods','opendocument','calc','pdf'], isClientReady: true
  },
  {
    id: 'odp-to-pdf', slug: 'odp-to-pdf', name: 'OpenDocument (ODP) a PDF', description: 'Convierte presentaciones ODP a PDF mediante LibreOffice.', category: 'documents', subcategory: 'Conversión', icon: 'Presentation', inputTypes: ['application/vnd.oasis.opendocument.presentation'], outputTypes: ['application/pdf'], acceptedExtensions: ['odp'], acceptedMimeTypes: ['application/vnd.oasis.opendocument.presentation'], processingMode: 'SERVER_SIDE', engine: 'server-libreoffice', requiresServer: true, keywords: ['odp','opendocument','impress','pdf'], isClientReady: true
  },

  // ==================== UTILITIES ====================
  {
    id: 'aspect-ratio-calculator',
    slug: 'aspect-ratio-calculator',
    name: 'Calculadora de Relación de Aspecto',
    description: 'Calcula dimensiones proporcionales para 16:9, 4:3, 21:9, 1:1 y ratios personalizados.',
    category: 'utilities',
    subcategory: 'Cálculo',
    icon: 'Ratio',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['aspect ratio', '16:9', '4:3', 'proporcion', 'pantalla', 'resolucion'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Generador de Contraseñas Seguras',
    description: 'Crea contraseñas criptográficamente seguras con puntuación de entropía y opciones personalizables.',
    category: 'utilities',
    subcategory: 'Seguridad',
    icon: 'Lock',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-crypto',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['password', 'contraseña', 'seguridad', 'entropia', 'generador'],
    popular: true,
    isClientReady: true
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'Conversor Unix Timestamp & Fechas',
    description: 'Convierte marcas de tiempo epoch (segundos y milisegundos) a fechas legibles en husos horarios locales y UTC.',
    category: 'utilities',
    subcategory: 'Tiempo',
    icon: 'Clock',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['timestamp', 'unix', 'epoch', 'utc', 'fecha', 'hora'],
    popular: false,
    isClientReady: true
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    name: 'Conversor de Almacenamiento Digital',
    description: 'Calcula conversiones exactas entre Bytes, KB, MB, GB, TB y PB con base 1024 (binaria) o base 1000 (decimal).',
    category: 'utilities',
    subcategory: 'Cálculo',
    icon: 'HardDrive',
    inputTypes: ['text/plain'],
    outputTypes: ['text/plain'],
    processingMode: 'CLIENT_SIDE',
    engine: 'browser-text',
    supportsBatch: false,
    supportsPreview: true,
    keywords: ['bytes', 'kb', 'mb', 'gb', 'tb', 'almacenamiento', 'disco', 'tamano'],
    popular: false,
    isClientReady: true
  },
  { id: 'url-shortener', slug: 'url-shortener', name: 'Acortador de URL', description: 'Crea un enlace corto con expiración y redirección segura.', category: 'developer', subcategory: 'Web', icon: 'Link', inputTypes: ['text/plain'], outputTypes: ['text/plain'], processingMode: 'SERVER_SIDE', engine: 'velyxora-links', requiresServer: true, supportsPreview: true, keywords: ['url','enlace','acortar','short link'], isClientReady: true },
  { id: 'icon-maker', slug: 'icon-maker', name: 'Icon Maker', description: 'Diseña iconos SVG locales con texto, emoji, forma y colores.', category: 'image', subcategory: 'Diseño', icon: 'Shapes', inputTypes: ['text/plain'], outputTypes: ['image/svg+xml'], processingMode: 'CLIENT_SIDE', engine: 'browser-svg', supportsPreview: true, keywords: ['icono','logo','svg','emoji'], isClientReady: true },
  { id: 'social-text-studio', slug: 'social-text-studio', name: 'Social Text Studio', description: 'Redacta y valida textos para redes sociales con contadores por plataforma.', category: 'text', subcategory: 'Redes sociales', icon: 'MessagesSquare', inputTypes: ['text/plain'], outputTypes: ['text/plain'], processingMode: 'CLIENT_SIDE', engine: 'browser-text', supportsPreview: true, keywords: ['instagram','x','tiktok','linkedin','social'], isClientReady: true },
  { id: 'emoji-tool', slug: 'emoji-tool', name: 'Emoji Tool', description: 'Explora, copia y guarda emojis favoritos localmente.', category: 'utilities', subcategory: 'Texto', icon: 'Smile', inputTypes: ['text/plain'], outputTypes: ['text/plain'], processingMode: 'CLIENT_SIDE', engine: 'browser-text', supportsPreview: true, keywords: ['emoji','copiar','favoritos'], isClientReady: true }
];

export const CATEGORIES_CONFIG = [
  { id: 'all', name: 'Todas las herramientas', icon: 'Grid' },
  { id: 'image', name: 'Imágenes', icon: 'Image' },
  { id: 'video', name: 'Video', icon: 'Video' },
  { id: 'audio', name: 'Audio', icon: 'Music' },
  { id: 'developer', name: 'Developer Tools', icon: 'Code' },
  { id: 'text', name: 'Texto', icon: 'FileText' },
  { id: 'qr-barcode', name: 'QR & Códigos', icon: 'QrCode' },
  { id: 'whatsapp', name: 'WhatsApp', icon: 'MessageCircle' },
  { id: 'media-downloader', name: 'Descargar Medios', icon: 'DownloadCloud' },
  { id: 'pdf', name: 'PDF', icon: 'FileSpreadsheet' },
  { id: 'documents', name: 'Documentos', icon: 'Files' },
  { id: 'utilities', name: 'Utilidades', icon: 'Wrench' },
] as const;

export const PUBLIC_TOOL_REGISTRY = TOOL_REGISTRY.filter((tool) => tool.public !== false);

// Product-facing navigation groups for the Free & Open Digital Toolkit shell.
// These intentionally map onto the existing internal `tool.category` values so
// that runners, deep links and stored favorites remain untouched.
export interface ToolkitGroup {
  id: string;
  name: string;
  description: string;
  icon: string;
  categories: string[];
  toolIds?: string[];
  excludeToolIds?: string[];
}

const CONVERTER_TOOL_IDS = [
  'csv-to-json',
  'json-to-csv',
  'markdown-to-html',
  'color-converter',
  'unit-converter',
  'timestamp-converter',
  'aspect-ratio-calculator',
];

export const TOOLKIT_GROUPS: ToolkitGroup[] = [
  { id: 'multimedia', name: 'Multimedia', description: 'Video, audio y descarga de medios.', icon: 'Video', categories: ['video', 'media-downloader'] },
  { id: 'documents', name: 'Documents', description: 'PDF y documentos de oficina.', icon: 'Files', categories: ['pdf', 'documents'] },
  { id: 'audio-speech', name: 'Audio & Speech', description: 'Edición de audio y futuras funciones de voz.', icon: 'Mic', categories: ['audio'] },
  { id: 'images', name: 'Images', description: 'Conversión, edición y optimización de imágenes.', icon: 'Image', categories: ['image'] },
  { id: 'whatsapp', name: 'WhatsApp Tools', description: 'Utilidades locales para WhatsApp.', icon: 'MessageCircle', categories: ['whatsapp'] },
  { id: 'converters', name: 'Converters', description: 'Conversión de formatos de datos y unidades.', icon: 'RefreshCw', categories: [], toolIds: CONVERTER_TOOL_IDS },
  { id: 'utilities', name: 'Utilities', description: 'Utilidades diarias de texto, QR y códigos.', icon: 'Wrench', categories: ['utilities', 'text', 'qr-barcode'], excludeToolIds: CONVERTER_TOOL_IDS },
  { id: 'dev-tools', name: 'Dev Tools', description: 'Herramientas para desarrolladores.', icon: 'Code', categories: ['developer'], excludeToolIds: CONVERTER_TOOL_IDS },
];

export interface PlannedTool {
  id: string;
  name: string;
  description: string;
  group: string;
  icon: string;
}

// Planned tools are surfaced for product discovery only. They are deliberately
// kept OUT of PUBLIC_TOOL_REGISTRY: they have no runner and must never be
// routed to ToolRunner or call any endpoint.
export const PLANNED_TOOL_REGISTRY: PlannedTool[] = [
  { id: 'compress-pdf', name: 'Comprimir PDF', description: 'Reduce el tamaño de un PDF localmente.', group: 'documents', icon: 'Minimize2' },
  { id: 'pdf-to-word', name: 'PDF a Word (DOCX)', description: 'Conversión de PDF a documento editable.', group: 'documents', icon: 'FileText' },
  { id: 'pdf-to-images', name: 'PDF a Imágenes', description: 'Exporta las páginas de un PDF como imágenes.', group: 'documents', icon: 'Images' },
  { id: 'speech-to-text', name: 'Voz a Texto', description: 'Transcripción de audio a texto (requiere un motor de reconocimiento).', group: 'audio-speech', icon: 'AudioLines' },
];

export function getToolkitGroup(groupId: string): ToolkitGroup | undefined {
  return TOOLKIT_GROUPS.find((group) => group.id === groupId);
}

export function getToolsForGroup(groupId: string): ToolDefinition[] {
  if (groupId === 'all') return PUBLIC_TOOL_REGISTRY;
  const group = getToolkitGroup(groupId);
  // Backward compatibility: legacy deep links such as /category/image still
  // resolve against the original internal category ids.
  if (!group) return PUBLIC_TOOL_REGISTRY.filter((tool) => tool.category === groupId);
  const explicitIds = new Set(group.toolIds ?? []);
  return PUBLIC_TOOL_REGISTRY.filter((tool) => {
    if (group.excludeToolIds?.includes(tool.id)) return false;
    return group.categories.includes(tool.category) || explicitIds.has(tool.id);
  });
}

export function getPlannedToolsForGroup(groupId: string): PlannedTool[] {
  if (groupId === 'all') return [];
  return PLANNED_TOOL_REGISTRY.filter((tool) => tool.group === groupId);
}

export type ToolRunnerKind = 'standard-file' | 'sticker-maker' | 'pdf' | 'image-advanced' | 'data-code' | 'utilities' | 'barcode' | 'qr' | 'text' | 'creative' | 'whatsapp' | 'speech';
export function getToolRunnerKind(tool: ToolDefinition): ToolRunnerKind | null {
  if (tool.category === 'whatsapp') return 'whatsapp';
  if (tool.id === 'text-to-speech') return 'speech';
  if (tool.id === 'sticker-maker') return 'sticker-maker';
  if (['url-shortener','icon-maker','social-text-studio','emoji-tool'].includes(tool.id)) return 'creative';
  if (tool.id === 'password-generator') return 'text';
  if (['images-to-pdf', 'text-to-pdf', 'merge-pdf', 'split-pdf'].includes(tool.id)) return 'pdf';
  if (tool.id === 'barcode-generator') return 'barcode';
  if (tool.id === 'qr-generator') return 'qr';
  if (['svg-to-png','svg-to-jpg','image-filters','image-watermark','color-picker-image','image-to-base64'].includes(tool.id)) return 'image-advanced';
  if (['csv-to-json','json-to-csv','markdown-to-html','color-converter','diff-checker'].includes(tool.id)) return 'data-code';
  if (tool.category === 'utilities' || tool.id === 'video-metadata-inspector') return 'utilities';
  if (['audio','video','image','documents'].includes(tool.category)) return 'standard-file';
  if (tool.category === 'developer' || tool.category === 'text') return 'text';
  return null;
}

export function getToolById(id: string): ToolDefinition | undefined {
  return PUBLIC_TOOL_REGISTRY.find(t => t.id === id || t.slug === id);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  if (category === 'all') return PUBLIC_TOOL_REGISTRY;
  return PUBLIC_TOOL_REGISTRY.filter(t => t.category === category);
}

export function searchTools(query: string): ToolDefinition[] {
  const clean = query.toLowerCase().trim();
  if (!clean) return PUBLIC_TOOL_REGISTRY;

  return PUBLIC_TOOL_REGISTRY.filter(tool => {
    const haystack = [tool.id, tool.slug, tool.name, tool.description, tool.category, tool.subcategory || '', ...tool.keywords, ...tool.inputTypes, ...tool.outputTypes].join(' ').toLowerCase();
    return clean.split(/\s+/).every((token) => haystack.includes(token));
  });
}
