import React, { useEffect, useMemo, useState } from 'react';
import { apiClient } from '../../services/apiClient';
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Sparkles, UserRound, Zap } from 'lucide-react';
import { CurrentUser, useAuth } from '../../auth/AuthContext';

const shell = 'mx-auto max-w-3xl rounded-2xl border border-white/10 bg-[#101218] p-5 sm:p-8';
const input = 'w-full rounded-xl border border-white/10 bg-[#08090D] px-4 py-3 text-sm outline-none focus:border-indigo-500';

export function AuthView({ onAuthenticated, onBack }: { onAuthenticated: (user: CurrentUser) => void; onBack: () => void }) {
  const { login, register: createAccount } = useAuth();
  const [register, setRegister] = useState(false); const [email, setEmail] = useState(() => localStorage.getItem('velyxora_remembered_email') || ''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [displayName, setDisplayName] = useState(''); const [remember, setRemember] = useState(Boolean(localStorage.getItem('velyxora_remembered_email'))); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; setError(''); if (register && password !== confirm) { setError('Las contraseñas no coinciden.'); return; } setBusy(true); try { const user = register ? await createAccount({ email, password, displayName }) : await login({ email, password }); if (remember) localStorage.setItem('velyxora_remembered_email', email.trim()); else localStorage.removeItem('velyxora_remembered_email'); onAuthenticated(user); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
  const field = (icon: React.ReactNode, child: React.ReactNode) => <div className="auth-field">{icon}{child}</div>;
  return <section className="auth-shell">
    <div className="auth-visual" aria-hidden="true"><div className="auth-brand-mark"><Zap /></div><p>VELYXORA PLATFORM</p><h2>Todo tu flujo digital,<br/><span>en un solo lugar.</span></h2><div className="auth-feature"><ShieldCheck/><span><strong>Sesiones seguras</strong><small>Protección por cookie HttpOnly y CSRF</small></span></div><div className="auth-feature"><Sparkles/><span><strong>Herramientas inteligentes</strong><small>Una experiencia rápida y consistente</small></span></div></div>
    <div className="auth-panel"><button onClick={onBack} className="auth-back">← Regresar</button><div className="auth-mobile-brand"><Zap/> VELYXORA</div><p className="auth-eyebrow">{register ? 'NUEVA CUENTA' : 'ACCESO SEGURO'}</p><h1>{register ? 'Crea tu espacio' : 'Bienvenido nuevamente'}</h1><p className="auth-copy">{register ? 'Empieza a potenciar tu flujo de trabajo.' : 'Ingresa para continuar donde lo dejaste.'}</p>
      <form onSubmit={submit} className="auth-form">{register && <label>Nombre{field(<UserRound/>, <input value={displayName} onChange={(e) => setDisplayName(e.target.value)} required maxLength={80} autoComplete="name" placeholder="Tu nombre" />)}</label>}<label>Correo electrónico{field(<Mail/>, <input type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nombre@correo.com" />)}</label><label>Contraseña<div className="auth-field"><LockKeyhole/><input type={showPassword ? 'text' : 'password'} required minLength={10} maxLength={200} autoComplete={register ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••••"/><button type="button" aria-label={showPassword ? 'Ocultar contraseña' : 'Mostrar contraseña'} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff/> : <Eye/>}</button></div></label>{register && <><label>Confirmar contraseña{field(<LockKeyhole/>, <input type={showPassword ? 'text' : 'password'} required minLength={10} maxLength={200} autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Repite tu contraseña" />)}</label><p className={password.length >= 10 ? 'password-ok' : 'password-hint'}>✓ Entre 10 y 200 caracteres</p></>}{!register && <label className="remember"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)}/><span>Recordar mi correo</span></label>}{error && <p role="alert" className="auth-error">{error}</p>}<button disabled={busy} className="auth-submit">{busy ? (register ? 'Creando cuenta…' : 'Iniciando sesión…') : (register ? 'Crear cuenta' : 'Iniciar sesión')}</button></form><p className="auth-switch">{register ? '¿Ya tienes una cuenta?' : '¿No tienes una cuenta?'} <button onClick={() => { setRegister(!register); setError(''); setPassword(''); setConfirm(''); }}>{register ? 'Iniciar sesión' : 'Crear cuenta'}</button></p>
    </div>
  </section>;
}

export function AccountView({ onBack }: { onBack: () => void }) {
  const [data, setData] = useState<any>(); const [paymentConfig, setPaymentConfig] = useState<any>();
  const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const [reference, setReference] = useState<Record<string, string>>({});
  const load = async () => { const [account, config] = await Promise.all([apiClient.auth.account(), apiClient.payments.config()]); setData(account); setPaymentConfig(config); };
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const createOrder = async (packageId: string) => { setBusy(packageId); setError(''); try { await apiClient.payments.createOrder(packageId, crypto.randomUUID()); await load(); } catch (e: any) { setError(e.message); } finally { setBusy(''); } };
  const submitReference = async (orderId: string) => { setBusy(orderId); setError(''); try { await apiClient.payments.submitReference(orderId, reference[orderId] || ''); await load(); } catch (e: any) { setError(e.message); } finally { setBusy(''); } };
  return <section className={`${shell} max-w-5xl`}><button onClick={onBack} className="mb-5 min-h-11 text-sm text-slate-400">← Regresar</button><h1 className="text-2xl font-bold">Mi cuenta</h1>
    {!data && !error && <p className="mt-6 text-sm text-slate-400">Cargando tu cuenta…</p>}{error && <p role="alert" className="mt-4 rounded-xl border border-red-500/20 p-3 text-sm text-red-300">{error}</p>}
    {data && <div className="mt-6 space-y-8">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Plan" value={data.plan?.code || 'FREE'} /><Metric label="Créditos disponibles" value={data.credits} /><Metric label="Estado" value="Activa" /><Metric label="Próximo reset" value={data.nextResetAt ? new Date(data.nextResetAt).toLocaleDateString() : '—'} /></div>
      <p className="break-all text-sm text-slate-400">{data.email}</p>
      <AccountList title="Ledger reciente" empty="No hay movimientos de créditos." items={data.ledger} render={(entry: any) => <><span>{entry.reason}</span><span className={entry.amount < 0 ? 'text-amber-300' : 'text-emerald-300'}>{entry.amount > 0 ? '+' : ''}{entry.amount}</span></>} />
      <AccountList title="Jobs recientes" empty="No hay jobs recientes." items={data.jobs} render={(job: any) => <><span>{job.toolId} · {new Date(job.createdAt).toLocaleString()}</span><span>{job.status} · {job.consumedCredits ?? 0} créditos</span></>} />
      <AccountList title="Historial sincronizado" empty="Tu historial sincronizado está vacío." items={data.history} render={(item: any) => <><span>{item.toolId} · {new Date(item.createdAt).toLocaleString()}</span><span>{item.status} · {item.processingType}{item.inputSize ? ` · ${formatBytes(item.inputSize)}` : ''}{item.creditsCost != null ? ` · ${item.creditsCost} créditos` : ''}</span></>} />
      {paymentConfig?.enabled && <div className="space-y-3"><div><h2 className="font-semibold">Pago beta con verificación manual</h2><p className="mt-1 text-xs text-slate-400">Envía el pago por Yape a {paymentConfig.displayName} · {paymentConfig.phone}. La acreditación no es automática.</p></div><div className="grid gap-3 sm:grid-cols-2">{Object.entries(paymentConfig.packages || {}).map(([id, pack]: any) => <button key={id} disabled={Boolean(busy)} onClick={() => createOrder(id)} className="min-h-11 rounded-xl border border-indigo-500/30 p-3 text-left disabled:opacity-50"><strong>{pack.planCode} beta</strong><span className="block text-xs text-slate-400">{pack.credits} créditos · {(pack.amountMinor / 100).toFixed(2)} {pack.currency}</span></button>)}</div></div>}
      <div className="space-y-3"><h2 className="font-semibold">Pagos Yape</h2>{!data.payments?.length ? <p className="rounded-xl bg-black/20 p-4 text-sm text-slate-400">No hay órdenes de pago.</p> : data.payments.map((order: any) => <article key={order.id} className="rounded-xl bg-black/20 p-4 text-sm"><div className="flex flex-col gap-1 sm:flex-row sm:justify-between"><span>{order.plan?.code || 'Paquete'} · {order.credits} créditos · {(order.amountMinor / 100).toFixed(2)} {order.currency}</span><span>{paymentLabel(order.status)}</span></div><p className="mt-1 text-xs text-slate-500">{new Date(order.createdAt).toLocaleString()}{order.reference ? ` · Referencia: ${order.reference}` : ''}</p>{order.status === 'PENDING_PAYMENT' && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><input aria-label="Referencia de pago" value={reference[order.id] || ''} onChange={(e) => setReference((old) => ({ ...old, [order.id]: e.target.value }))} className={input} placeholder="Referencia enviada" /><button disabled={busy === order.id} onClick={() => submitReference(order.id)} className="min-h-11 shrink-0 rounded-xl bg-indigo-600 px-4 disabled:opacity-50">Enviar referencia</button></div>}</article>)}</div>
    </div>}
  </section>;
}

export function AdminView({ onBack }: { onBack: () => void }) {
  const [dashboard, setDashboard] = useState<any>(); const [users, setUsers] = useState<any[]>([]); const [payments, setPayments] = useState<any[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('ALL');
  const load = () => Promise.all([apiClient.auth.adminDashboard(), apiClient.auth.adminUsers(), apiClient.auth.adminPayments()]).then(([d,u,p]) => { setDashboard(d); setUsers(u); setPayments(p); });
  useEffect(() => { load().catch((e) => setError(e.message)); }, []);
  const review = async (order: any, decision: 'APPROVE' | 'REJECT') => { const reason = window.prompt(decision === 'APPROVE' ? 'Razón de aprobación' : 'Razón de rechazo'); if (!reason) return; setBusy(order.id); setError(''); try { await apiClient.auth.reviewPayment(order.id, decision, reason); await load(); } catch (e: any) { setError(e.message); } finally { setBusy(''); } };
  const filteredUsers = useMemo(() => users.filter((user) => (statusFilter === 'ALL' || user.status === statusFilter) && user.email.toLowerCase().includes(query.trim().toLowerCase())), [users, query, statusFilter]);
  const pendingPayments = payments.filter((order) => order.status === 'PENDING_REVIEW');
  return <section className="mx-auto max-w-6xl overflow-hidden rounded-3xl border border-white/10 bg-[#0d1018] shadow-2xl">
    <header className="border-b border-white/10 bg-gradient-to-r from-indigo-500/10 to-cyan-500/5 p-5 sm:p-8"><button onClick={onBack} className="min-h-11 text-sm text-slate-400">← Volver a mi cuenta</button><div className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold tracking-[.24em] text-indigo-400">CONSOLA VELYXORA</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Panel administrativo</h1><p className="mt-1 text-sm text-slate-400">Supervisión segura de usuarios, créditos y pagos.</p></div><span className="w-fit rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-300">● Sistema operativo</span></div></header>
    <div className="p-5 sm:p-8">{error && <p role="alert" className="mb-5 rounded-xl border border-red-500/20 p-3 text-red-300">{error}</p>}{dashboard && <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Usuarios totales" value={dashboard.users} /><Metric label="Usuarios activos" value={dashboard.activeUsers} /><Metric label="Procesamientos" value={dashboard.jobs} /><Metric label="Créditos netos" value={dashboard.netCredits} /></div>}
      <div className="mt-9 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Gestión de usuarios</h2><p className="text-xs text-slate-500">{filteredUsers.length} resultados</p></div><div className="flex flex-col gap-2 sm:flex-row"><input aria-label="Buscar usuarios" className={`${input} sm:w-64`} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por correo…"/><select aria-label="Filtrar por estado" className={`${input} sm:w-40`} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="ALL">Todos</option><option value="ACTIVE">Activos</option><option value="SUSPENDED">Suspendidos</option></select></div></div>
      <div className="mt-4 hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-white/10 text-xs text-slate-500"><th className="p-3">Usuario</th><th>Plan</th><th>Créditos</th><th>Estado</th><th>Registro</th></tr></thead><tbody>{filteredUsers.map((user) => <tr key={user.id} className="border-b border-white/5 transition hover:bg-white/[.025]"><td className="p-3 font-medium">{user.email}</td><td>{user.plan}</td><td>{user.credits}</td><td><StatusBadge value={user.status}/></td><td className="text-slate-400">{new Date(user.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>
      <div className="mt-4 grid gap-3 md:hidden">{filteredUsers.map((user) => <article key={user.id} className="rounded-2xl border border-white/8 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><p className="break-all text-sm font-semibold">{user.email}</p><StatusBadge value={user.status}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span className="text-slate-500">Plan<strong className="mt-1 block text-slate-200">{user.plan}</strong></span><span className="text-slate-500">Créditos<strong className="mt-1 block text-slate-200">{user.credits}</strong></span><span className="text-slate-500">Registro<strong className="mt-1 block text-slate-200">{new Date(user.createdAt).toLocaleDateString()}</strong></span></div></article>)}</div>
      <h2 className="mt-10 font-semibold">Pagos pendientes de revisión</h2><div className="mt-3 space-y-3">{pendingPayments.length ? pendingPayments.map((order) => <article key={order.id} className="rounded-2xl border border-white/8 bg-black/20 p-4 text-sm"><p className="font-medium">{order.credits} créditos · {(order.amountMinor / 100).toFixed(2)} {order.currency}</p><p className="mt-1 break-all text-xs text-slate-400">Referencia: {order.reference || '—'} · {new Date(order.createdAt).toLocaleString()}</p><div className="mt-3 flex flex-wrap gap-2"><button disabled={Boolean(busy)} onClick={() => review(order, 'APPROVE')} className="min-h-11 rounded-xl bg-emerald-700 px-4 disabled:opacity-50">Aprobar</button><button disabled={Boolean(busy)} onClick={() => review(order, 'REJECT')} className="min-h-11 rounded-xl border border-rose-500/40 px-4 text-rose-300 disabled:opacity-50">Rechazar</button></div></article>) : <p className="rounded-xl bg-black/20 p-4 text-sm text-slate-400">No hay pagos pendientes de revisión.</p>}</div>
    </div>
  </section>;
}
function StatusBadge({ value }: { value: string }) { const active = value === 'ACTIVE'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${active ? 'bg-emerald-500/10 text-emerald-300' : 'bg-amber-500/10 text-amber-300'}`}>{active ? 'ACTIVO' : 'SUSPENDIDO'}</span>; }
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl border border-white/5 bg-black/20 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function AccountList({ title, empty, items, render }: { title: string; empty: string; items: any[]; render: (item: any) => React.ReactNode }) { return <div><h2 className="mb-3 font-semibold">{title}</h2>{items?.length ? <ul className="space-y-2 text-sm">{items.map((item, index) => <li key={item.id || index} className="flex flex-col justify-between gap-1 rounded-lg bg-black/20 p-3 sm:flex-row">{render(item)}</li>)}</ul> : <p className="rounded-xl bg-black/20 p-4 text-sm text-slate-400">{empty}</p>}</div>; }
function formatBytes(value: string | number) { const bytes = Number(value); if (!Number.isFinite(bytes)) return '—'; return bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function paymentLabel(status: string) { return ({ PENDING_PAYMENT: 'Pendiente de pago', PENDING_REVIEW: 'En revisión manual', APPROVED: 'Aprobado', REJECTED: 'Rechazado', CANCELLED: 'Cancelado' } as Record<string, string>)[status] || status; }
