import React, { useEffect, useState } from 'react';
import { apiClient } from '../../services/apiClient';

export type CurrentUser = { id: string; email: string; displayName?: string | null; role: 'USER'|'ADMIN'; status: string };
const shell = 'mx-auto max-w-3xl rounded-2xl border border-white/10 bg-[#101218] p-5 sm:p-8';
const input = 'w-full rounded-xl border border-white/10 bg-[#08090D] px-4 py-3 text-sm outline-none focus:border-indigo-500';

export function AuthView({ onAuthenticated, onBack }: { onAuthenticated: (user: CurrentUser) => void; onBack: () => void }) {
  const [register, setRegister] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [displayName, setDisplayName] = useState(''); const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { const result = register ? await apiClient.auth.register(email, password, displayName) : await apiClient.auth.login(email, password); onAuthenticated(result.user); } catch (e: any) { setError(e.message); } };
  return <section className={shell}><button onClick={onBack} className="mb-5 min-h-11 text-sm text-slate-400">← Regresar</button><h1 className="text-2xl font-bold">{register ? 'Crear cuenta' : 'Iniciar sesión'}</h1><form onSubmit={submit} className="mt-6 space-y-4">{register && <input className={input} value={displayName} onChange={(e) => setDisplayName(e.target.value)} placeholder="Nombre visible (opcional)" />}<input className={input} type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" /><input className={input} type="password" required minLength={10} autoComplete={register ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Contraseña" />{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<button className="min-h-11 w-full rounded-xl bg-indigo-600 font-semibold">{register ? 'Registrarme' : 'Entrar'}</button></form><button onClick={() => setRegister(!register)} className="mt-4 min-h-11 text-sm text-indigo-400">{register ? 'Ya tengo cuenta' : 'Crear una cuenta'}</button></section>;
}

export function AccountView({ onBack }: { onBack: () => void }) {
  const [data, setData] = useState<any>(); const [error, setError] = useState(''); useEffect(() => { apiClient.auth.account().then(setData).catch((e) => setError(e.message)); }, []);
  return <section className={shell}><button onClick={onBack} className="mb-5 min-h-11 text-sm text-slate-400">← Regresar</button><h1 className="text-2xl font-bold">Mi cuenta</h1>{error && <p className="mt-4 text-red-400">{error}</p>}{data && <div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Plan" value={data.plan?.code || 'FREE'} /><Metric label="Créditos" value={data.credits} /><Metric label="Próximo reset" value={data.nextResetAt ? new Date(data.nextResetAt).toLocaleDateString() : '—'} /></div><p className="text-sm text-slate-400">{data.email}</p><h2 className="font-semibold">Consumo reciente</h2><ul className="space-y-2 text-sm">{data.ledger.map((entry: any, index: number) => <li key={index} className="flex justify-between rounded-lg bg-black/20 p-3"><span>{entry.reason}</span><span>{entry.amount > 0 ? '+' : ''}{entry.amount}</span></li>)}</ul></div>}</section>;
}

export function AdminView({ onBack }: { onBack: () => void }) {
  const [dashboard, setDashboard] = useState<any>(); const [users, setUsers] = useState<any[]>([]); const [error, setError] = useState(''); useEffect(() => { Promise.all([apiClient.auth.adminDashboard(), apiClient.auth.adminUsers()]).then(([d,u]) => { setDashboard(d); setUsers(u); }).catch((e) => setError(e.message)); }, []);
  return <section className={shell}><button onClick={onBack} className="mb-5 min-h-11 text-sm text-slate-400">← Regresar</button><h1 className="text-2xl font-bold">Administración</h1>{error && <p className="mt-4 text-red-400">{error}</p>}{dashboard && <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Usuarios" value={dashboard.users} /><Metric label="Activos" value={dashboard.activeUsers} /><Metric label="Jobs" value={dashboard.jobs} /><Metric label="Créditos netos" value={dashboard.netCredits} /></div>}<h2 className="mt-8 font-semibold">Usuarios</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-slate-400"><th className="p-2">Email</th><th>Plan</th><th>Créditos</th><th>Estado</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t border-white/5"><td className="p-2">{user.email}</td><td>{user.plan}</td><td>{user.credits}</td><td>{user.status}</td></tr>)}</tbody></table></div></section>;
}
function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="rounded-xl border border-white/5 bg-black/20 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
