import { useState } from 'react';
import { apiClient } from '../../services/apiClient';
import { useAuth } from '../../auth/AuthContext';

const field = 'min-h-12 w-full rounded-xl border border-white/10 bg-black/25 px-4 text-sm outline-none focus:border-indigo-500';
export function FeedbackView({ kind, onBack }: { kind: 'complaint' | 'suggestion'; onBack: () => void }) {
  const { user } = useAuth(); const complaint = kind === 'complaint'; const [form, setForm] = useState<Record<string,string>>({ claimantName: user?.displayName || '', email: user?.email || '', type: 'RECLAMO', category: 'MEJORA', subject: '', title: '', detail: '', description: '' }); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const update=(key:string,value:string)=>setForm((old)=>({...old,[key]:value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const result=complaint?await apiClient.feedback.createComplaint(form):await apiClient.feedback.createSuggestion(form);setMessage(complaint?`Solicitud recibida. Código de seguimiento: ${result.trackingCode}`:'Gracias. Tu sugerencia fue enviada.');}catch(error:any){setMessage(error.message);}finally{setBusy(false)}};
  if (!complaint && !user) return <section className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-[#101218] p-6"><h1 className="text-xl font-bold">Sugerencias y mejoras</h1><p className="mt-3 text-slate-400">Inicia sesión para enviar y consultar sugerencias.</p><button onClick={onBack} className="mt-5 min-h-11 text-indigo-400">Regresar</button></section>;
  return <section className="mx-auto max-w-2xl rounded-3xl border border-white/10 bg-[#101218] p-5 shadow-2xl sm:p-8"><button onClick={onBack} className="min-h-11 text-sm text-slate-400">← Regresar</button><p className="mt-4 text-[10px] font-bold tracking-[.22em] text-indigo-400">VELYXORA · BETA</p><h1 className="mt-2 text-2xl font-bold">{complaint?'Libro de Reclamaciones':'Sugerencias y mejoras'}</h1><p className="mt-2 text-sm text-slate-400">{complaint?'Registraremos tu solicitud y te entregaremos un código de seguimiento.':'Ayúdanos a priorizar mejoras reales para la plataforma.'}</p><form onSubmit={submit} className="mt-7 grid gap-4">{complaint&&<><input className={field} required minLength={2} maxLength={100} placeholder="Nombre del reclamante" value={form.claimantName} onChange={(e)=>update('claimantName',e.target.value)}/><input className={field} type="email" required maxLength={254} placeholder="Email de contacto" value={form.email} onChange={(e)=>update('email',e.target.value)}/><select className={field} value={form.type} onChange={(e)=>update('type',e.target.value)}><option value="RECLAMO">Reclamo</option><option value="QUEJA">Queja</option></select></>}{!complaint&&<select className={field} value={form.category} onChange={(e)=>update('category',e.target.value)}><option value="MEJORA">Mejora</option><option value="NUEVA_FUNCION">Nueva función</option><option value="PROBLEMA_UX">Problema de experiencia</option><option value="OTRO">Otro</option></select>}<input className={field} required minLength={3} maxLength={complaint?160:120} placeholder={complaint?'Asunto':'Título'} value={complaint?form.subject:form.title} onChange={(e)=>update(complaint?'subject':'title',e.target.value)}/><textarea className={`${field} min-h-36 py-3`} required minLength={complaint?20:10} maxLength={complaint?4000:2500} placeholder={complaint?'Describe tu reclamo o queja':'Describe tu propuesta'} value={complaint?form.detail:form.description} onChange={(e)=>update(complaint?'detail':'description',e.target.value)}/>{message&&<p role="status" className="rounded-xl border border-indigo-500/20 bg-indigo-500/5 p-3 text-sm text-indigo-200">{message}</p>}<button disabled={busy} className="min-h-12 rounded-xl bg-indigo-600 font-semibold disabled:opacity-50">{busy?'Enviando…':'Enviar'}</button></form></section>;
}
