import React from 'react';
import { ArrowLeft, Cloud, Lock, Network } from 'lucide-react';
import { VelyxoraLogo } from '../logo/VelyxoraLogo';

export function LegalView({page,onBack}:{page:'privacy'|'terms'|'about';onBack:()=>void}) {
  const title=page==='privacy'?'Política de Privacidad':page==='terms'?'Términos de Servicio':'Acerca de VELYXORA';
  return <section className="mx-auto w-full max-w-3xl space-y-7 py-2 text-sm leading-relaxed text-slate-300"><button onClick={onBack} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-3"><ArrowLeft className="h-4 w-4"/>Regresar</button><header className="border-b border-white/10 pb-6 text-center"><VelyxoraLogo variant="full" size="lg" className="justify-center"/><p className="mt-4 text-[10px] font-bold tracking-[.24em] text-indigo-400">VELYXORA · BETA</p><h1 className="mt-2 text-2xl font-bold text-white">{title}</h1></header>
  {page==='about'&&<><p><strong className="text-white">VELYXORA</strong> es una plataforma de conversión, procesamiento multimedia y utilidades digitales.</p><div className="grid gap-3 sm:grid-cols-3"><Policy icon={<Lock/>} title="LOCAL">Se procesa en tu dispositivo mediante Canvas, Web Audio y Web Crypto cuando corresponde.</Policy><Policy icon={<Cloud/>} title="SERVER">Se procesa temporalmente en los servidores de VELYXORA con motores disponibles como FFmpeg y LibreOffice. Los archivos están sujetos al TTL configurado.</Policy><Policy icon={<Network/>} title="EXTERNAL">Puede depender de servicios externos. Su disponibilidad y compatibilidad pueden cambiar.</Policy></div><p>La beta evoluciona con pruebas reales: herramientas, límites, créditos y compatibilidad pueden ajustarse.</p></>}
  {page==='privacy'&&<><LegalSection title="1. Datos de cuenta">Podemos tratar email, nombre visible, hash de contraseña, sesiones, rol, estado y plan. Nunca almacenamos contraseñas en texto plano.</LegalSection><LegalSection title="2. Operación">Se registran créditos, ledger, jobs, historial sincronizado y metadata mínima necesaria para operar y proteger el servicio.</LegalSection><LegalSection title="3. Pagos beta">PaymentOrder conserva referencia, importe, estado y revisión administrativa. Yape se verifica manualmente. No almacenamos tarjetas ni CVV. Si eliges contactar por WhatsApp, se abre un mensaje prellenado con datos mínimos de tu solicitud; puedes revisarlo o modificarlo y tú decides enviarlo. Al continuar, WhatsApp/Meta también tratará esos datos conforme a sus propios términos.</LegalSection><LegalSection title="4. Archivos y proveedores">Las operaciones LOCAL no sacan el archivo del dispositivo para convertirlo. Las SERVER lo transmiten temporalmente y lo eliminan conforme al TTL configurado. Las EXTERNAL pueden interactuar con proveedores compatibles.</LegalSection><LegalSection title="5. Compartir">Cuando eliges Compartir, VELYXORA entrega el resultado al menú nativo del navegador o sistema operativo. La capa Share no sube el contenido a otro servicio ni publica directamente en redes sociales; tú eliges el destino y confirmas la acción.</LegalSection><LegalSection title="6. Feedback y seguridad">Conservamos reclamaciones, sugerencias y respuestas administrativas. No almacenamos cookies sociales, sesiones de terceros ni credenciales de proveedores externos.</LegalSection><LegalSection title="7. Solicitudes sobre tus datos">Puedes usar el Libro de Reclamaciones para solicitar acceso, rectificación, actualización, oposición o eliminación/anonimización cuando corresponda. La atención dependerá de la identidad, el alcance y la conservación necesaria para seguridad, contabilidad y trazabilidad.</LegalSection></>}
  {page==='terms'&&<><LegalSection title="1. Servicio beta">VELYXORA está en beta. Funcionalidades, límites y créditos pueden cambiar; los motores o proveedores externos pueden dejar de ser compatibles.</LegalSection><LegalSection title="2. Uso aceptable y derechos">Solo debes procesar contenido propio o autorizado. Fraude, abuso, automatización maliciosa o violaciones de políticas pueden ocasionar suspensión o ban.</LegalSection><LegalSection title="3. Media y restricciones">No se permite evadir DRM, autenticación, paywalls ni acceder a contenido privado o restringido. VELYXORA no recibe cookies externas ni garantiza compatibilidad permanente.</LegalSection><LegalSection title="4. Enlaces cortos y abuso">El acortador admite destinos HTTP y HTTPS sin inspeccionar automáticamente su temática. No puede utilizarse para phishing, malware, fraude, spam abusivo, suplantación, distribución ilícita, ataques ni evasión de controles de seguridad. Los enlaces reportados pueden revisarse y deshabilitarse.</LegalSection><LegalSection title="5. Pagos manuales">Yape se revisa manualmente; no existe verificación automática y los créditos solo se acreditan tras aprobación. Un rechazo puede incluir un motivo apropiado.</LegalSection><LegalSection title="6. Disponibilidad">El servicio se ofrece según disponibilidad durante la beta, sin promesas de precisión absoluta o continuidad permanente.</LegalSection></>}
  </section>;
}
function Policy({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <article className="rounded-2xl border border-white/10 bg-[#101218] p-4"><span className="text-indigo-400 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><h2 className="mt-3 font-mono font-bold text-white">{title}</h2><p className="mt-2 text-xs text-slate-400">{children}</p></article>}
function LegalSection({title,children}:{title:string;children:React.ReactNode}){return <div><h2 className="font-semibold text-white">{title}</h2><p className="mt-2">{children}</p></div>}
